### ISSUE TITLE
[A-PHASE] Las plataformas salen de la zona visible

### ISSUE THREAD

**Issue by roybos-nine** [mbpmm/Hop-Hop-Knight#1]
Al saltar hacia una plataforma cuando esta se cierra, no para y sigue su trayectoria hasta salir de la pantalla visible. El personaje se queda trabado a un costado y es imposible seguir jugando.

https://drive.google.com/open?id=11yXviJBjPIrrQh2kFgiYKzJ8TENSSToQ

**Comment by mbpmm** [comment]
El problema estas solucionado en la version publicada aca: https://mbpmm.itch.io/hop-hop-knight

**Comment by KryEdge** [comment]
Chequeado otra vez en version 0.7
CLOSED
