### ISSUE TITLE
[A PHASE] Inconcistencia en los bordes de las plataformas

### ISSUE THREAD

**Issue by roybos-nine** [mbpmm/Hop-Hop-Knight#2]
A veces los bordes de las plataformas son solidos y no se pueden traspasar
Para recrearlo hay que saltar hacia el borde de alguna plataforma

https://drive.google.com/open?id=1255yyKSi289tPwNWbTJWmz4P8Hef8Ihj

**Comment by mbpmm** [comment]
El problema estas solucionado en la version publicada aca: https://mbpmm.itch.io/hop-hop-knight

**Comment by KryEdge** [comment]
Chequeado otra vez en version 0.7
CLOSED
