### ISSUE TITLE
[A-PHASE] la barra de salto no desaparese una ves muerto

### ISSUE THREAD

**Issue by roybos-nine** [mbpmm/Hop-Hop-Knight#3]
Si un enemigo te mata justo cuando vas a hacer un salto la barra no se esconde y queda con el personaje.

https://drive.google.com/open?id=120-jiVwJKBtrYDoXMHvtosA7rWOzycPW

**Comment by KryEdge** [comment]
Chequeado otra vez en version 0.7
CLOSED
