### ISSUE TITLE
[A-PHASE] Babosa se eleva al chocarla desde abajo

### ISSUE THREAD

**Issue by roybos-nine** [mbpmm/Hop-Hop-Knight#4]
Cuando haces un salto debajo de una babosa a veces esta se mueve hacia arriba.

https://drive.google.com/open?id=1212MdJVO7ZWZoIQW1JYzpoiLgrw4QAVq

**Comment by mbpmm** [comment]
El problema estas solucionado en la version publicada aca: https://mbpmm.itch.io/hop-hop-knight

**Comment by KryEdge** [comment]
Chequeado otra vez en version 0.7
CLOSED
