### ISSUE TITLE
[A-PHASE] Si tocamos la pantalla mientras el personaje vuela, la animacion cambia

### ISSUE THREAD

**Issue by KryEdge** [mbpmm/Hop-Hop-Knight#5]
Si conseguimos las 5 gemas y el personaje usa su "power up" de volar, si mientras realiza esto tocamos la pantalla, el personaje cambiara su animación por la de carga de salto hasta que aterrice.
Paso 1: Entrar en una partida
Paso 2: Conseguir 5 gemas
Paso 3: Intentar "saltar" mientras el personaje vuela

https://drive.google.com/open?id=1Ai_231LIUi79Ka2KdNF9mfy0l29-Jejx

**Comment by mbpmm** [comment]
Solucionado en la versión 1.0
